CREATE TABLE users (
 id BIGSERIAL PRIMARY KEY,
 name VARCHAR(255),
 email VARCHAR(255) UNIQUE NOT NULL,
 password VARCHAR(500) NOT NULL,
 role VARCHAR(50) NOT NULL,
 created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_users_email ON users(email);